#!/usr/bin/env bash

set -e
benchmarks=( argot ensime fimpp joos kiama phantm scalaxb scalisp see squeryl tictactoe )

date

echo "getting stats ..."
for benchmark in ${benchmarks[@]}
do
  ./get-stats ${benchmark}
done
date