#!/usr/bin/env bash

set -e
benchmark=$1
tca_expand_this="tca-expand-this"
tca_expand="tca-expand"
tca_bounds="tca-bounds"
tca_names="tca-names"
ra="ra"
wala_rta="wala-rta"

# make some directories
mkdir -p dist/${tca_expand_this}/${benchmark}
mkdir -p dist/${tca_expand}/${benchmark}
mkdir -p dist/${tca_bounds}/${benchmark}
mkdir -p dist/${tca_names}/${benchmark}
mkdir -p dist/${ra}/${benchmark}
mkdir -p dist/${wala_rta}/${benchmark}
mkdir -p dist/scalac/${benchmark}

# run the source-level analyses
echo -e "\t running tca-expand-this ..."
ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=tca-expand-this > dist/${tca_expand_this}/${benchmark}/tca-expand-this-log
echo -e "\t running tca-expand ..."
ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=tca-expand      > dist/${tca_expand}/${benchmark}/tca-expand-log
echo -e "\t running tca-bounds ..."
ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=tca-bounds      > dist/${tca_bounds}/${benchmark}/tca-bounds-log
echo -e "\t running tca-names ..."
ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=tca-names       > dist/${tca_names}/${benchmark}/tca-names-log
echo -e "\t running ra ..."
ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=ra          > dist/${ra}/${benchmark}/ra-log
echo -e "\t archiving dependencies for WALA ..."
ant bm-deps.jar -Dbm=${benchmark}                              > dist/${tca_expand_this}/${benchmark}/deps-log

# run wala
echo -e "\t running rta-wala ..."
./walacg ${benchmark} > dist/${wala_rta}/${benchmark}/wala-rta-log

# run scalac
echo -e "\t running scalac ..."
ant -logger org.apache.tools.ant.listener.ProfileLogger bm.jar -Dbm=${benchmark} -Danalysis=scalac > dist/scalac/${benchmark}/scalac-log