#!/usr/bin/env bash

set -e
benchmark=$1
tca_expand_this="tca-expand-this"
tca_expand="tca-expand"
tca_bounds="tca-bounds"
ra_inst="ra-inst"
ra_all="ra-all"
wala_rta="wala-rta"

# make some directories
mkdir -p dist/${tca_expand_this}/${benchmark}
mkdir -p dist/${tca_expand}/${benchmark}
mkdir -p dist/${tca_bounds}/${benchmark}
mkdir -p dist/${ra_inst}/${benchmark}
mkdir -p dist/${ra_all}/${benchmark}
mkdir -p dist/${wala_rta}/${benchmark}

# run the source-level analyses
ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=tca-expand-this > dist/${tca_expand_this}/${benchmark}/tca-expand-this-log
ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=tca-expand      > dist/${tca_expand}/${benchmark}/tca-expand-log
ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=tca-bounds      > dist/${tca_bounds}/${benchmark}/tca-bounds-log
ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=ra-inst         > dist/${ra_inst}/${benchmark}/ra-inst-log
ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=ra-all          > dist/${ra_all}/${benchmark}/ra-all-log
ant bm-deps.jar -Dbm=${benchmark}                              > dist/${tca_expand_this}/${benchmark}/deps-log

# run wala
./walacg ${benchmark} > dist/${wala_rta}/${benchmark}/wala-rta-log