#!/usr/bin/env bash

set -e
tca_expand="tca-expand"
benchmarks=( argot ensime fimpp kiama phantm scalaxb scalisp see squeryl tictactoe )

date

echo "running tca-expand"
for benchmark in ${benchmarks[@]}
do
  mkdir -p dist/${tca_expand}/${benchmark}
  ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=tca-expand      > dist/${tca_expand}/${benchmark}/tca-expand-log
done

#echo "generating LaTeX files"
java -cp $SCALA_HOME/lib/scala-library.jar:$SCALA_HOME/lib/scala-reflect.jar:latex.jar ca.uwaterloo.scalacg.experiments.LatexGenerator
date