#!/usr/bin/env bash

set -e
benchmarks=( argot ensime fimpp joos kiama phantm scalariform scalaxb scalisp see squeryl tictactoe )

date

echo "running analyses"
for benchmark in ${benchmarks[@]}
do
  ./run ${benchmark}
done

echo "generating LaTeX files"
java -jar latex.jar
date