#!/usr/bin/env bash

set -e
benchmarks=( argot ensime fimpp kiama phantm scalaxb scalisp see squeryl tictactoe )

date

echo "running ra"
for benchmark in ${benchmarks[@]}
do
  mkdir -p dist/ra/${benchmark}
  ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=ra      > dist/ra/${benchmark}/ra-log
done

#echo "generating LaTeX files"
#java -cp $SCALA_HOME/lib/scala-library.jar:$SCALA_HOME/lib/scala-reflect.jar:latex.jar ca.uwaterloo.scalacg.experiments.LatexGenerator
date