#!/usr/bin/env bash

set -e
tca_expand_this="tca-expand-this"
benchmarks=( argot ensime fimpp kiama phantm scalaxb scalisp see squeryl tictactoe )

date

echo "running tca-expand-this"
for benchmark in ${benchmarks[@]}
do
  mkdir -p dist/${tca_expand_this}/${benchmark}
  ant bm-plugin.jar -Dbm=${benchmark} -Danalysis=tca-expand-this      > dist/${tca_expand_this}/${benchmark}/tca-expand-this-log
done

#echo "generating LaTeX files"
#java -cp $SCALA_HOME/lib/scala-library.jar:$SCALA_HOME/lib/scala-reflect.jar:latex.jar ca.uwaterloo.scalacg.experiments.LatexGenerator
date