#!/usr/bin/env bash

set -e
benchmarks=( argot ensime fimpp joos kiama phantm scalariform scalaxb scalisp see squeryl tictactoe )

date

for benchmark in ${benchmarks[@]}
do
  ./run ${benchmark}
done
date