#!/usr/bin/env bash

set -e
benchmark=$1
cg="callgraph-summary.txt.gzip"
tca_expand_this="tca-expand-this"
tca_expand="tca-expand"
tca_bounds="tca-bounds"
tca_names="tca-names"
ra="ra"
wala_rta="wala-rta"

# diff call graphs
./cgdiff dist/${tca_expand_this}/${benchmark}/${cg} dist/${tca_expand}/${benchmark}/${cg}
./cgdiff dist/${tca_expand}/${benchmark}/${cg} dist/${tca_bounds}/${benchmark}/${cg}
./cgdiff dist/${tca_bounds}/${benchmark}/${cg} dist/${tca_names}/${benchmark}/${cg}
./cgdiff dist/${tca_names}/${benchmark}/${cg} dist/${ra}/${benchmark}/${cg}

# success
echo ${benchmark} success