#!/usr/bin/env bash

set -e
benchmarks=( argot casbah ensime factorie fimpp kiama phantm scalap scalariform scalaxb scalisp see squeryl tictactoe )

date

echo "asserting subset sanity checks ..."
for benchmark in ${benchmarks[@]}
do
  ./sanity ${benchmark}
done
date