#!/usr/bin/env bash

set -e
benchmarks=( argot ensime fimpp joos kiama phantm scalaxb scalisp see squeryl tictactoe )

date

echo "compiling benchmarks"
for benchmark in ${benchmarks[@]}
do
  mkdir -p dist/scalac/${benchmark}
  ant -logger org.apache.tools.ant.listener.ProfileLogger bm.jar -Dbm=${benchmark} -Danalysis=scalac > dist/scalac/${benchmark}/scalac-log
done
date
