#!/usr/bin/env bash

set -e
benchmarks=( argot ensime fimpp joos kiama phantm scalaxb scalisp see squeryl tictactoe )

date

echo "compiling benchmarks"
for benchmark in ${benchmarks[@]}
do
  mkdir -p dist/scalac/${benchmark}
  ant bm.jar -Dbm=${benchmark} -Danalysis=scalac   -Dthis=false -Dsuper=false > dist/scalac/${benchmark}/scalac-log
done
date